use signal_orchestrate::{COORDINATION_INTERFACE_RUST, COORDINATION_INTERFACE_SOURCE};

#[test]
fn coordination_interface_is_role_free_and_strictly_generated() {
    assert!(
        COORDINATION_INTERFACE_SOURCE
            .starts_with("Interface.{1 0 0}\n[]\n{\n  []\n  []\n  []\n  [")
    );
    assert!(COORDINATION_INTERFACE_SOURCE.contains("LaneAssignment.{"));
    assert!(COORDINATION_INTERFACE_SOURCE.contains("ScopeReference.["));
    assert!(COORDINATION_INTERFACE_SOURCE.contains("Worktree.{"));
    assert!(COORDINATION_INTERFACE_RUST.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n"
    ));
}

#[test]
fn build_uses_one_exact_verified_bootstrap_boundary() {
    let manifest = include_str!("../Cargo.toml");
    let build = include_str!("../build.rs");

    assert!(manifest.contains("9e36587c85bd69357e9042729ba2df0052799756"));
    assert_eq!(manifest.matches("schema-rust =").count(), 1);
    assert_eq!(build.matches("BootstrapInterfaceGeneration").count(), 2);
    assert!(build.contains("BootstrapTransactionAssembler"));
    assert!(build.contains("RustTypePath::try_new"));
    assert!(build.contains("CargoEthosSourceMetadata"));
    assert!(build.contains("publish_owned_source_directory"));
}
