// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2VMM6 ( z2VRMe ,) ;
pub struct z2VXoy(Vec<z2VMSd>);
impl z2VXoy {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VMSd>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VMSd> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VMSd> {
        self.0
    }
}
pub struct z2VbrZ {
    pub field_0: z2VY5t,
    pub field_1: z2VdfL,
    pub field_2: z2VQzo,
    pub field_3: z2VTai,
    pub field_4: z2Vbir,
    pub field_5: z2VTmk,
    pub field_6: z2VVpY,
    pub field_7: z2VXDo,
}
pub enum z2VWF8 {z2VRfw , z2VNqm ,} 
pub struct z2VL6b(std::string::String);
impl z2VL6b {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VaeM(std::string::String);
impl z2VaeM {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VSNu(u64);
impl z2VSNu {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2Vdsm {
    pub field_0: z2VLd7,
    pub field_1: z2VWF8,
}
pub struct z2VWJQ(std::string::String);
impl z2VWJQ {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VdfL(std::string::String);
impl z2VdfL {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2Vbrw(std::string::String);
impl z2Vbrw {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VZSC(Vec<z2VL6b>);
impl z2VZSC {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VL6b>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VL6b> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VL6b> {
        self.0
    }
}
pub struct z2VUHv {
    pub field_0: z2VRMe,
    pub field_1: z2VeE8,
    pub field_2: z2VbqA,
}
pub struct z2VY5t(std::string::String);
impl z2VY5t {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VTai(std::string::String);
impl z2VTai {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VVpY(u64);
impl z2VVpY {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VbqA(std::string::String);
impl z2VbqA {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VMSd {
    pub field_0: z2VRhW,
    pub field_1: z2VbqA,
    pub field_2: z2VVpY,
    pub field_3: z2VSNu,
}
pub struct z2VPwf {
    pub field_0: z2VRhW,
    pub field_1: z2VRMe,
    pub field_2: z2VbqA,
}
pub struct z2Vepu(Vec<z2VbrZ>);
impl z2Vepu {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VbrZ>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VbrZ> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VbrZ> {
        self.0
    }
}
pub enum z2VRhW {z2VLVx ( z2VWJQ ,) , z2VWRs ( z2VQzo ,) ,} 
pub struct z2VRMe(std::string::String);
impl z2VRMe {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VLd7 ( z2VZSC ,) ;
pub enum z2Vbir {z2VNV3 , z2VNbR , z2VV2G , z2VbHo , z2VVBr ,} 
pub struct z2VY3M {
    pub field_0: z2VRMe,
    pub field_1: z2VeE8,
}
pub struct z2VQzo(std::string::String);
impl z2VQzo {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VKnV(Vec<z2VPwf>);
impl z2VKnV {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VPwf>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VPwf> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VPwf> {
        self.0
    }
}
pub enum z2VXDG {z2VRaU , z2VX34 , z2VUc8 , z2VTTz ,} 
pub struct z2VeE8(Vec<z2VRhW>);
impl z2VeE8 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VRhW>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VRhW> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VRhW> {
        self.0
    }
}
pub enum z2VXDo {z2VPX3 , z2VWWj , z2VVpj ,} 
pub struct z2VTtj {
    pub field_0: z2VaeM,
    pub field_1: z2Vbrw,
    pub field_2: z2Vdsm,
    pub field_3: z2VPu7,
}
pub struct z2VPu7(std::string::String);
impl z2VPu7 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VXaB {
    pub field_0: z2VRMe,
    pub field_1: z2VKnV,
}
pub struct z2Vbze {
    pub field_0: z2VRMe,
    pub field_1: z2VeE8,
    pub field_2: z2Vepu,
}
pub struct z2VTmk(std::string::String);
impl z2VTmk {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
