//! The ordinary Orchestrate wire contract.
//!
//! `ethos/signal.ethos` is the authored source and the only interface;
//! `src/generated/signal.rs` is its projection, regenerated by ethos-zero and
//! held byte-identical by `build.rs`.
//!
//! The contract's identity on the wire is the digest of that source. A
//! connection is greeted once with it, and two peers built from different
//! sources refuse each other rather than negotiate — there is no version
//! range, no minor tolerance and no compatibility path.

pub mod generated;
pub use generated::signal::*;

/// The authored Ethos source this contract is generated from, and the one
/// artefact its wire identity is computed over.
pub const ETHOS: &str = include_str!("../ethos/signal.ethos");

/// The identity is borne by the query root because the querying side is the
/// side that greets: a peer that can construct a [`Query`] is a peer that can
/// open the connection it travels on.
impl signal::Contracted for Query {
    const CONTRACT_SOURCE: &'static str = ETHOS;
}
