// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

pub type RoleIdentifier = String;

pub type RoleName = RoleIdentifier;

pub type RoleToken = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Role(pub Vec<RoleToken>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum LaneAuthority {
    Structural,
    Support,
}

pub type LaneIdentifier = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneRegistration {
    pub lane: LaneIdentifier,
    pub role: Role,
    pub authority: LaneAuthority,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum HarnessKind {
    Codex,
    Claude,
}

pub type WirePath = String;

pub type TaskToken = String;

pub type ScopeReason = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ScopeReference {
    Path(WirePath),
    Task(TaskToken),
}

pub type TimestampNanos = Integer;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleClaim {
    pub role: RoleName,
    pub scopes: Vec<ScopeReference>,
    pub reason: ScopeReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleRelease(pub RoleName);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleHandoff {
    pub from: RoleName,
    pub to: RoleName,
    pub scopes: Vec<ScopeReference>,
    pub reason: ScopeReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Observation {
    Roles,
    Lanes,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivitySubmission {
    pub role: RoleName,
    pub scope: ScopeReference,
    pub reason: ScopeReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivityQuery {
    pub limit: Integer,
    pub filters: Vec<ActivityFilter>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ActivityFilter {
    RoleFilter(RoleName),
    PathPrefix(WirePath),
    TaskToken(TaskToken),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservationSubscription {
    pub include_operations: Boolean,
    pub include_effects: Boolean,
}

pub type ObservationToken = Integer;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClaimAcceptance {
    pub role: RoleName,
    pub scopes: Vec<ScopeReference>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClaimRejection {
    pub role: RoleName,
    pub conflicts: Vec<ScopeConflict>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ScopeConflict {
    pub scope: ScopeReference,
    pub held_by: RoleName,
    pub held_reason: ScopeReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReleaseAcknowledgment {
    pub role: RoleName,
    pub released_scopes: Vec<ScopeReference>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HandoffAcceptance {
    pub from: RoleName,
    pub to: RoleName,
    pub scopes: Vec<ScopeReference>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HandoffRejection {
    pub from: RoleName,
    pub to: RoleName,
    pub reason: HandoffRejectionReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum HandoffRejectionReason {
    SourceRoleDoesNotHold,
    TargetRoleConflict(Vec<ScopeConflict>),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleSnapshot {
    pub roles: Vec<RoleStatus>,
    pub recent_activity: Vec<Activity>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LanesObserved(pub Vec<LaneRegistration>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleStatus {
    pub role: RoleName,
    pub harness: HarnessKind,
    pub claims: Vec<ClaimEntry>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClaimEntry {
    pub scope: ScopeReference,
    pub reason: ScopeReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Activity {
    pub role: RoleName,
    pub scope: ScopeReference,
    pub reason: ScopeReason,
    pub stamped_at: TimestampNanos,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivityAcknowledgment(pub Integer);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivityList(pub Vec<Activity>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DownstreamComponent {
    Router,
    Harness,
    Terminal,
    Message,
    Mind,
    System,
    Introspect,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ApplicationFailureReason {
    Unreachable,
    Rejected,
    Unimplemented,
    TimedOut,
    Unknown,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplicationSuccess {
    pub component: DownstreamComponent,
    pub detail: ScopeReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplicationFailure {
    pub component: DownstreamComponent,
    pub reason: ApplicationFailureReason,
    pub detail: ScopeReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PartialApplied {
    pub succeeded: Vec<ApplicationSuccess>,
    pub failed: Vec<ApplicationFailure>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservationOpened(pub ObservationToken);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservationClosed(pub ObservationToken);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OperationKind {
    Claim,
    Release,
    Handoff,
    Observe,
    Submit,
    Query,
    Watch,
    Unwatch,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EffectOutcome {
    Applied,
    Removed,
    Changed,
    Observed,
    StreamOpened,
    StreamClosed,
    NoChange,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OperationReceived(pub OperationKind);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EffectEmitted {
    pub operation: OperationKind,
    pub outcome: EffectOutcome,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ObservationEvent {
    OperationReceived(OperationReceived),
    EffectEmitted(EffectEmitted),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Claim(RoleClaim),
    Release(RoleRelease),
    Handoff(RoleHandoff),
    Observe(Observation),
    Submit(ActivitySubmission),
    Query(ActivityQuery),
    Watch(ObservationSubscription),
    Unwatch(ObservationToken),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ClaimAcceptance(ClaimAcceptance),
    ClaimRejection(ClaimRejection),
    ReleaseAcknowledgment(ReleaseAcknowledgment),
    HandoffAcceptance(HandoffAcceptance),
    HandoffRejection(HandoffRejection),
    RoleSnapshot(RoleSnapshot),
    LanesObserved(LanesObserved),
    ActivityAcknowledgment(ActivityAcknowledgment),
    ActivityList(ActivityList),
    PartialApplied(PartialApplied),
    ObservationOpened(ObservationOpened),
    ObservationClosed(ObservationClosed),
}

impl Role {
    pub fn new(payload: Vec<RoleToken>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RoleToken> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RoleToken> {
        self.0
    }
}
impl From<Vec<RoleToken>> for Role {
    fn from(payload: Vec<RoleToken>) -> Self {
        Self::new(payload)
    }
}

impl RoleRelease {
    pub fn new(payload: RoleName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RoleName {
        &self.0
    }
    pub fn into_payload(self) -> RoleName {
        self.0
    }
}
impl From<RoleName> for RoleRelease {
    fn from(payload: RoleName) -> Self {
        Self::new(payload)
    }
}

impl LanesObserved {
    pub fn new(payload: Vec<LaneRegistration>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<LaneRegistration> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<LaneRegistration> {
        self.0
    }
}
impl From<Vec<LaneRegistration>> for LanesObserved {
    fn from(payload: Vec<LaneRegistration>) -> Self {
        Self::new(payload)
    }
}

impl ActivityAcknowledgment {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
impl From<Integer> for ActivityAcknowledgment {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

impl ActivityList {
    pub fn new(payload: Vec<Activity>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Activity> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Activity> {
        self.0
    }
}
impl From<Vec<Activity>> for ActivityList {
    fn from(payload: Vec<Activity>) -> Self {
        Self::new(payload)
    }
}

impl ObservationOpened {
    pub fn new(payload: ObservationToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObservationToken {
        &self.0
    }
    pub fn into_payload(self) -> ObservationToken {
        self.0
    }
}
impl From<ObservationToken> for ObservationOpened {
    fn from(payload: ObservationToken) -> Self {
        Self::new(payload)
    }
}

impl ObservationClosed {
    pub fn new(payload: ObservationToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObservationToken {
        &self.0
    }
    pub fn into_payload(self) -> ObservationToken {
        self.0
    }
}
impl From<ObservationToken> for ObservationClosed {
    fn from(payload: ObservationToken) -> Self {
        Self::new(payload)
    }
}

impl OperationReceived {
    pub fn new(payload: OperationKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OperationKind {
        &self.0
    }
    pub fn into_payload(self) -> OperationKind {
        self.0
    }
}
impl From<OperationKind> for OperationReceived {
    fn from(payload: OperationKind) -> Self {
        Self::new(payload)
    }
}

impl ScopeReference {
    pub fn path(payload: WirePath) -> Self {
        Self::Path(payload)
    }
    pub fn task(payload: TaskToken) -> Self {
        Self::Task(payload)
    }
}

impl ActivityFilter {
    pub fn role_filter(payload: RoleName) -> Self {
        Self::RoleFilter(payload)
    }
    pub fn path_prefix(payload: WirePath) -> Self {
        Self::PathPrefix(payload)
    }
    pub fn task_token(payload: TaskToken) -> Self {
        Self::TaskToken(payload)
    }
}

impl HandoffRejectionReason {
    pub fn target_role_conflict(payload: Vec<ScopeConflict>) -> Self {
        Self::TargetRoleConflict(payload)
    }
}

impl ObservationEvent {
    pub fn operation_received(payload: OperationKind) -> Self {
        Self::OperationReceived(OperationReceived::new(payload))
    }
    pub fn effect_emitted(payload: EffectEmitted) -> Self {
        Self::EffectEmitted(payload)
    }
}

impl Input {
    pub fn claim(payload: RoleClaim) -> Self {
        Self::Claim(payload)
    }
    pub fn release(payload: RoleName) -> Self {
        Self::Release(RoleRelease::new(payload))
    }
    pub fn handoff(payload: RoleHandoff) -> Self {
        Self::Handoff(payload)
    }
    pub fn observe(payload: Observation) -> Self {
        Self::Observe(payload)
    }
    pub fn submit(payload: ActivitySubmission) -> Self {
        Self::Submit(payload)
    }
    pub fn query(payload: ActivityQuery) -> Self {
        Self::Query(payload)
    }
    pub fn watch(payload: ObservationSubscription) -> Self {
        Self::Watch(payload)
    }
    pub fn unwatch(payload: ObservationToken) -> Self {
        Self::Unwatch(payload)
    }
}

impl Output {
    pub fn claim_acceptance(payload: ClaimAcceptance) -> Self {
        Self::ClaimAcceptance(payload)
    }
    pub fn claim_rejection(payload: ClaimRejection) -> Self {
        Self::ClaimRejection(payload)
    }
    pub fn release_acknowledgment(payload: ReleaseAcknowledgment) -> Self {
        Self::ReleaseAcknowledgment(payload)
    }
    pub fn handoff_acceptance(payload: HandoffAcceptance) -> Self {
        Self::HandoffAcceptance(payload)
    }
    pub fn handoff_rejection(payload: HandoffRejection) -> Self {
        Self::HandoffRejection(payload)
    }
    pub fn role_snapshot(payload: RoleSnapshot) -> Self {
        Self::RoleSnapshot(payload)
    }
    pub fn lanes_observed(payload: Vec<LaneRegistration>) -> Self {
        Self::LanesObserved(LanesObserved::new(payload))
    }
    pub fn activity_acknowledgment(payload: Integer) -> Self {
        Self::ActivityAcknowledgment(ActivityAcknowledgment::new(payload))
    }
    pub fn activity_list(payload: Vec<Activity>) -> Self {
        Self::ActivityList(ActivityList::new(payload))
    }
    pub fn partial_applied(payload: PartialApplied) -> Self {
        Self::PartialApplied(payload)
    }
    pub fn observation_opened(payload: ObservationToken) -> Self {
        Self::ObservationOpened(ObservationOpened::new(payload))
    }
    pub fn observation_closed(payload: ObservationToken) -> Self {
        Self::ObservationClosed(ObservationClosed::new(payload))
    }
}

impl From<OperationReceived> for ObservationEvent {
    fn from(payload: OperationReceived) -> Self {
        Self::OperationReceived(payload)
    }
}

impl From<EffectEmitted> for ObservationEvent {
    fn from(payload: EffectEmitted) -> Self {
        Self::EffectEmitted(payload)
    }
}

impl From<RoleClaim> for Input {
    fn from(payload: RoleClaim) -> Self {
        Self::Claim(payload)
    }
}

impl From<RoleRelease> for Input {
    fn from(payload: RoleRelease) -> Self {
        Self::Release(payload)
    }
}

impl From<RoleHandoff> for Input {
    fn from(payload: RoleHandoff) -> Self {
        Self::Handoff(payload)
    }
}

impl From<Observation> for Input {
    fn from(payload: Observation) -> Self {
        Self::Observe(payload)
    }
}

impl From<ActivitySubmission> for Input {
    fn from(payload: ActivitySubmission) -> Self {
        Self::Submit(payload)
    }
}

impl From<ActivityQuery> for Input {
    fn from(payload: ActivityQuery) -> Self {
        Self::Query(payload)
    }
}

impl From<ObservationSubscription> for Input {
    fn from(payload: ObservationSubscription) -> Self {
        Self::Watch(payload)
    }
}

impl From<ClaimAcceptance> for Output {
    fn from(payload: ClaimAcceptance) -> Self {
        Self::ClaimAcceptance(payload)
    }
}

impl From<ClaimRejection> for Output {
    fn from(payload: ClaimRejection) -> Self {
        Self::ClaimRejection(payload)
    }
}

impl From<ReleaseAcknowledgment> for Output {
    fn from(payload: ReleaseAcknowledgment) -> Self {
        Self::ReleaseAcknowledgment(payload)
    }
}

impl From<HandoffAcceptance> for Output {
    fn from(payload: HandoffAcceptance) -> Self {
        Self::HandoffAcceptance(payload)
    }
}

impl From<HandoffRejection> for Output {
    fn from(payload: HandoffRejection) -> Self {
        Self::HandoffRejection(payload)
    }
}

impl From<RoleSnapshot> for Output {
    fn from(payload: RoleSnapshot) -> Self {
        Self::RoleSnapshot(payload)
    }
}

impl From<LanesObserved> for Output {
    fn from(payload: LanesObserved) -> Self {
        Self::LanesObserved(payload)
    }
}

impl From<ActivityAcknowledgment> for Output {
    fn from(payload: ActivityAcknowledgment) -> Self {
        Self::ActivityAcknowledgment(payload)
    }
}

impl From<ActivityList> for Output {
    fn from(payload: ActivityList) -> Self {
        Self::ActivityList(payload)
    }
}

impl From<PartialApplied> for Output {
    fn from(payload: PartialApplied) -> Self {
        Self::PartialApplied(payload)
    }
}

impl From<ObservationOpened> for Output {
    fn from(payload: ObservationOpened) -> Self {
        Self::ObservationOpened(payload)
    }
}

impl From<ObservationClosed> for Output {
    fn from(payload: ObservationClosed) -> Self {
        Self::ObservationClosed(payload)
    }
}

#[cfg(feature = "nota-text")]
impl Role {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LaneAuthority {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LaneRegistration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl HarnessKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ScopeReference {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RoleClaim {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RoleRelease {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RoleHandoff {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Observation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ActivitySubmission {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ActivityQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ActivityFilter {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ObservationSubscription {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ClaimAcceptance {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ClaimRejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ScopeConflict {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ReleaseAcknowledgment {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl HandoffAcceptance {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl HandoffRejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl HandoffRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RoleSnapshot {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl LanesObserved {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RoleStatus {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ClaimEntry {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Activity {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ActivityAcknowledgment {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ActivityList {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DownstreamComponent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ApplicationFailureReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ApplicationSuccess {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ApplicationFailure {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PartialApplied {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ObservationOpened {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ObservationClosed {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl OperationKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EffectOutcome {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl OperationReceived {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl EffectEmitted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ObservationEvent {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_CLAIM: u64 = 0x0000000000000000;
    pub const INPUT_RELEASE: u64 = 0x0001000000000000;
    pub const INPUT_HANDOFF: u64 = 0x0002000000000000;
    pub const INPUT_OBSERVE: u64 = 0x0003000000000000;
    pub const INPUT_SUBMIT: u64 = 0x0004000000000000;
    pub const INPUT_QUERY: u64 = 0x0005000000000000;
    pub const INPUT_WATCH: u64 = 0x0006000000000000;
    pub const INPUT_UNWATCH: u64 = 0x0007000000000000;
    pub const OUTPUT_CLAIM_ACCEPTANCE: u64 = 0x0100000000000000;
    pub const OUTPUT_CLAIM_REJECTION: u64 = 0x0101000000000000;
    pub const OUTPUT_RELEASE_ACKNOWLEDGMENT: u64 = 0x0102000000000000;
    pub const OUTPUT_HANDOFF_ACCEPTANCE: u64 = 0x0103000000000000;
    pub const OUTPUT_HANDOFF_REJECTION: u64 = 0x0104000000000000;
    pub const OUTPUT_ROLE_SNAPSHOT: u64 = 0x0105000000000000;
    pub const OUTPUT_LANES_OBSERVED: u64 = 0x0106000000000000;
    pub const OUTPUT_ACTIVITY_ACKNOWLEDGMENT: u64 = 0x0107000000000000;
    pub const OUTPUT_ACTIVITY_LIST: u64 = 0x0108000000000000;
    pub const OUTPUT_PARTIAL_APPLIED: u64 = 0x0109000000000000;
    pub const OUTPUT_OBSERVATION_OPENED: u64 = 0x010A000000000000;
    pub const OUTPUT_OBSERVATION_CLOSED: u64 = 0x010B000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Claim,
    Release,
    Handoff,
    Observe,
    Submit,
    Query,
    Watch,
    Unwatch,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    ClaimAcceptance,
    ClaimRejection,
    ReleaseAcknowledgment,
    HandoffAcceptance,
    HandoffRejection,
    RoleSnapshot,
    LanesObserved,
    ActivityAcknowledgment,
    ActivityList,
    PartialApplied,
    ObservationOpened,
    ObservationClosed,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Claim(_) => InputRoute::Claim,
            Self::Release(_) => InputRoute::Release,
            Self::Handoff(_) => InputRoute::Handoff,
            Self::Observe(_) => InputRoute::Observe,
            Self::Submit(_) => InputRoute::Submit,
            Self::Query(_) => InputRoute::Query,
            Self::Watch(_) => InputRoute::Watch,
            Self::Unwatch(_) => InputRoute::Unwatch,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Claim(_) => short_header::INPUT_CLAIM,
            Self::Release(_) => short_header::INPUT_RELEASE,
            Self::Handoff(_) => short_header::INPUT_HANDOFF,
            Self::Observe(_) => short_header::INPUT_OBSERVE,
            Self::Submit(_) => short_header::INPUT_SUBMIT,
            Self::Query(_) => short_header::INPUT_QUERY,
            Self::Watch(_) => short_header::INPUT_WATCH,
            Self::Unwatch(_) => short_header::INPUT_UNWATCH,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_CLAIM => Ok(InputRoute::Claim),
            short_header::INPUT_RELEASE => Ok(InputRoute::Release),
            short_header::INPUT_HANDOFF => Ok(InputRoute::Handoff),
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            short_header::INPUT_SUBMIT => Ok(InputRoute::Submit),
            short_header::INPUT_QUERY => Ok(InputRoute::Query),
            short_header::INPUT_WATCH => Ok(InputRoute::Watch),
            short_header::INPUT_UNWATCH => Ok(InputRoute::Unwatch),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::ClaimAcceptance(_) => OutputRoute::ClaimAcceptance,
            Self::ClaimRejection(_) => OutputRoute::ClaimRejection,
            Self::ReleaseAcknowledgment(_) => OutputRoute::ReleaseAcknowledgment,
            Self::HandoffAcceptance(_) => OutputRoute::HandoffAcceptance,
            Self::HandoffRejection(_) => OutputRoute::HandoffRejection,
            Self::RoleSnapshot(_) => OutputRoute::RoleSnapshot,
            Self::LanesObserved(_) => OutputRoute::LanesObserved,
            Self::ActivityAcknowledgment(_) => OutputRoute::ActivityAcknowledgment,
            Self::ActivityList(_) => OutputRoute::ActivityList,
            Self::PartialApplied(_) => OutputRoute::PartialApplied,
            Self::ObservationOpened(_) => OutputRoute::ObservationOpened,
            Self::ObservationClosed(_) => OutputRoute::ObservationClosed,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::ClaimAcceptance(_) => short_header::OUTPUT_CLAIM_ACCEPTANCE,
            Self::ClaimRejection(_) => short_header::OUTPUT_CLAIM_REJECTION,
            Self::ReleaseAcknowledgment(_) => short_header::OUTPUT_RELEASE_ACKNOWLEDGMENT,
            Self::HandoffAcceptance(_) => short_header::OUTPUT_HANDOFF_ACCEPTANCE,
            Self::HandoffRejection(_) => short_header::OUTPUT_HANDOFF_REJECTION,
            Self::RoleSnapshot(_) => short_header::OUTPUT_ROLE_SNAPSHOT,
            Self::LanesObserved(_) => short_header::OUTPUT_LANES_OBSERVED,
            Self::ActivityAcknowledgment(_) => {
                short_header::OUTPUT_ACTIVITY_ACKNOWLEDGMENT
            }
            Self::ActivityList(_) => short_header::OUTPUT_ACTIVITY_LIST,
            Self::PartialApplied(_) => short_header::OUTPUT_PARTIAL_APPLIED,
            Self::ObservationOpened(_) => short_header::OUTPUT_OBSERVATION_OPENED,
            Self::ObservationClosed(_) => short_header::OUTPUT_OBSERVATION_CLOSED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_CLAIM_ACCEPTANCE => Ok(OutputRoute::ClaimAcceptance),
            short_header::OUTPUT_CLAIM_REJECTION => Ok(OutputRoute::ClaimRejection),
            short_header::OUTPUT_RELEASE_ACKNOWLEDGMENT => {
                Ok(OutputRoute::ReleaseAcknowledgment)
            }
            short_header::OUTPUT_HANDOFF_ACCEPTANCE => Ok(OutputRoute::HandoffAcceptance),
            short_header::OUTPUT_HANDOFF_REJECTION => Ok(OutputRoute::HandoffRejection),
            short_header::OUTPUT_ROLE_SNAPSHOT => Ok(OutputRoute::RoleSnapshot),
            short_header::OUTPUT_LANES_OBSERVED => Ok(OutputRoute::LanesObserved),
            short_header::OUTPUT_ACTIVITY_ACKNOWLEDGMENT => {
                Ok(OutputRoute::ActivityAcknowledgment)
            }
            short_header::OUTPUT_ACTIVITY_LIST => Ok(OutputRoute::ActivityList),
            short_header::OUTPUT_PARTIAL_APPLIED => Ok(OutputRoute::PartialApplied),
            short_header::OUTPUT_OBSERVATION_OPENED => Ok(OutputRoute::ObservationOpened),
            short_header::OUTPUT_OBSERVATION_CLOSED => Ok(OutputRoute::ObservationClosed),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

