// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleName(RoleIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleToken(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleTokens(Vec<RoleToken>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Role(RoleTokens);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum LaneAuthority {
    Structural,
    Support,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneRegistration {
    pub lane: LaneIdentifier,
    pub role: Role,
    pub authority: LaneAuthority,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum HarnessKind {
    Codex,
    Claude,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TaskToken(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ScopeReason(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ScopeReference {
    Path(WirePath),
    Task(TaskToken),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TimestampNanos(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RepositoryName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BranchName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PurposeText(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WorktreeStatus {
    Active,
    Merged,
    Archived,
    Recycled,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum PushedState {
    Unpushed,
    Pushed,
    AncestorOfMain,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Worktree {
    pub repository: RepositoryName,
    pub branch: BranchName,
    pub path: WirePath,
    pub owning_lane: LaneName,
    pub worktree_status: WorktreeStatus,
    pub purpose: PurposeText,
    pub last_activity: TimestampNanos,
    pub pushed_state: PushedState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ScopeReferences(Vec<ScopeReference>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivityFilters(Vec<ActivityFilter>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ScopeConflicts(Vec<ScopeConflict>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaneRegistrations(Vec<LaneRegistration>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Worktrees(Vec<Worktree>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleStatuses(Vec<RoleStatus>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Activities(Vec<Activity>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClaimEntries(Vec<ClaimEntry>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplicationSuccesses(Vec<ApplicationSuccess>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplicationFailures(Vec<ApplicationFailure>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleClaim {
    pub role: RoleName,
    pub scopes: ScopeReferences,
    pub reason: ScopeReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleRelease(RoleName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleHandoff {
    pub from: RoleName,
    pub to: RoleName,
    pub scopes: ScopeReferences,
    pub reason: ScopeReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum Observation {
    Roles,
    Lanes,
    Worktrees,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivitySubmission {
    pub role: RoleName,
    pub scope: ScopeReference,
    pub reason: ScopeReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivityQuery {
    pub limit: Integer,
    pub filters: ActivityFilters,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ActivityFilter {
    RoleFilter(RoleName),
    PathPrefix(WirePath),
    TaskToken(TaskToken),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservationSubscription {
    pub include_operations: Boolean,
    pub include_effects: Boolean,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservationToken(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClaimAcceptance {
    pub role: RoleName,
    pub scopes: ScopeReferences,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClaimRejection {
    pub role: RoleName,
    pub conflicts: ScopeConflicts,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ScopeConflict {
    pub scope: ScopeReference,
    pub held_by: RoleName,
    pub held_reason: ScopeReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReleaseAcknowledgment {
    pub role: RoleName,
    pub released_scopes: ScopeReferences,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HandoffAcceptance {
    pub from: RoleName,
    pub to: RoleName,
    pub scopes: ScopeReferences,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HandoffRejection {
    pub from: RoleName,
    pub to: RoleName,
    pub reason: HandoffRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum HandoffRejectionReason {
    SourceRoleDoesNotHold,
    TargetRoleConflict(ScopeConflicts),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleSnapshot {
    pub roles: RoleStatuses,
    pub recent_activity: Activities,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LanesObserved(LaneRegistrations);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorktreesObserved(Worktrees);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleStatus {
    pub role: RoleName,
    pub harness: HarnessKind,
    pub claims: ClaimEntries,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClaimEntry {
    pub scope: ScopeReference,
    pub reason: ScopeReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Activity {
    pub role: RoleName,
    pub scope: ScopeReference,
    pub reason: ScopeReason,
    pub stamped_at: TimestampNanos,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivityAcknowledgment(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActivityList(Activities);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DownstreamComponent {
    Router,
    Harness,
    Terminal,
    Message,
    Mind,
    System,
    Introspect,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ApplicationFailureReason {
    Unreachable,
    Rejected,
    Unimplemented,
    TimedOut,
    Unknown,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplicationSuccess {
    pub component: DownstreamComponent,
    pub detail: ScopeReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ApplicationFailure {
    pub component: DownstreamComponent,
    pub reason: ApplicationFailureReason,
    pub detail: ScopeReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PartialApplied {
    pub succeeded: ApplicationSuccesses,
    pub failed: ApplicationFailures,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservationOpened(ObservationToken);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservationClosed(ObservationToken);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    Claim,
    Release,
    Handoff,
    Observe,
    Submit,
    Query,
    Watch,
    Unwatch,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum EffectOutcome {
    Applied,
    Removed,
    Changed,
    Observed,
    StreamOpened,
    StreamClosed,
    NoChange,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OperationReceived(OperationKind);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EffectEmitted {
    pub operation: OperationKind,
    pub outcome: EffectOutcome,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ObservationEvent {
    OperationReceived(OperationReceived),
    EffectEmitted(EffectEmitted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Claim(RoleClaim),
    Release(RoleRelease),
    Handoff(RoleHandoff),
    Observe(Observation),
    Submit(ActivitySubmission),
    Query(ActivityQuery),
    Watch(ObservationSubscription),
    Unwatch(ObservationToken),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ClaimAcceptance(ClaimAcceptance),
    ClaimRejection(ClaimRejection),
    ReleaseAcknowledgment(ReleaseAcknowledgment),
    HandoffAcceptance(HandoffAcceptance),
    HandoffRejection(HandoffRejection),
    RoleSnapshot(RoleSnapshot),
    LanesObserved(LanesObserved),
    WorktreesObserved(WorktreesObserved),
    ActivityAcknowledgment(ActivityAcknowledgment),
    ActivityList(ActivityList),
    PartialApplied(PartialApplied),
    ObservationOpened(ObservationOpened),
    ObservationClosed(ObservationClosed),
}

#[rustfmt::skip]
impl RoleIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RoleIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleName {
    pub fn new(payload: RoleIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RoleIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> RoleIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<RoleIdentifier> for RoleName {
    fn from(payload: RoleIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleToken {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RoleToken {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleTokens {
    pub fn new(payload: Vec<RoleToken>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RoleToken> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RoleToken> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RoleToken>> for RoleTokens {
    fn from(payload: Vec<RoleToken>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Role {
    pub fn new(payload: RoleTokens) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RoleTokens {
        &self.0
    }
    pub fn into_payload(self) -> RoleTokens {
        self.0
    }
}
#[rustfmt::skip]
impl From<RoleTokens> for Role {
    fn from(payload: RoleTokens) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LaneIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for LaneIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TaskToken {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TaskToken {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ScopeReason {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ScopeReason {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TimestampNanos {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TimestampNanos {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RepositoryName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RepositoryName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BranchName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for BranchName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LaneName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for LaneName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PurposeText {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PurposeText {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ScopeReferences {
    pub fn new(payload: Vec<ScopeReference>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ScopeReference> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ScopeReference> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ScopeReference>> for ScopeReferences {
    fn from(payload: Vec<ScopeReference>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ActivityFilters {
    pub fn new(payload: Vec<ActivityFilter>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ActivityFilter> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ActivityFilter> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ActivityFilter>> for ActivityFilters {
    fn from(payload: Vec<ActivityFilter>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ScopeConflicts {
    pub fn new(payload: Vec<ScopeConflict>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ScopeConflict> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ScopeConflict> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ScopeConflict>> for ScopeConflicts {
    fn from(payload: Vec<ScopeConflict>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LaneRegistrations {
    pub fn new(payload: Vec<LaneRegistration>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<LaneRegistration> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<LaneRegistration> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<LaneRegistration>> for LaneRegistrations {
    fn from(payload: Vec<LaneRegistration>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Worktrees {
    pub fn new(payload: Vec<Worktree>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Worktree> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Worktree> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Worktree>> for Worktrees {
    fn from(payload: Vec<Worktree>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleStatuses {
    pub fn new(payload: Vec<RoleStatus>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RoleStatus> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RoleStatus> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RoleStatus>> for RoleStatuses {
    fn from(payload: Vec<RoleStatus>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Activities {
    pub fn new(payload: Vec<Activity>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Activity> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Activity> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Activity>> for Activities {
    fn from(payload: Vec<Activity>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ClaimEntries {
    pub fn new(payload: Vec<ClaimEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ClaimEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ClaimEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ClaimEntry>> for ClaimEntries {
    fn from(payload: Vec<ClaimEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ApplicationSuccesses {
    pub fn new(payload: Vec<ApplicationSuccess>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ApplicationSuccess> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ApplicationSuccess> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ApplicationSuccess>> for ApplicationSuccesses {
    fn from(payload: Vec<ApplicationSuccess>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ApplicationFailures {
    pub fn new(payload: Vec<ApplicationFailure>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ApplicationFailure> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ApplicationFailure> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ApplicationFailure>> for ApplicationFailures {
    fn from(payload: Vec<ApplicationFailure>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleRelease {
    pub fn new(payload: RoleName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RoleName {
        &self.0
    }
    pub fn into_payload(self) -> RoleName {
        self.0
    }
}
#[rustfmt::skip]
impl From<RoleName> for RoleRelease {
    fn from(payload: RoleName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObservationToken {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for ObservationToken {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LanesObserved {
    pub fn new(payload: LaneRegistrations) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LaneRegistrations {
        &self.0
    }
    pub fn into_payload(self) -> LaneRegistrations {
        self.0
    }
}
#[rustfmt::skip]
impl From<LaneRegistrations> for LanesObserved {
    fn from(payload: LaneRegistrations) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorktreesObserved {
    pub fn new(payload: Worktrees) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Worktrees {
        &self.0
    }
    pub fn into_payload(self) -> Worktrees {
        self.0
    }
}
#[rustfmt::skip]
impl From<Worktrees> for WorktreesObserved {
    fn from(payload: Worktrees) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ActivityAcknowledgment {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for ActivityAcknowledgment {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ActivityList {
    pub fn new(payload: Activities) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Activities {
        &self.0
    }
    pub fn into_payload(self) -> Activities {
        self.0
    }
}
#[rustfmt::skip]
impl From<Activities> for ActivityList {
    fn from(payload: Activities) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObservationOpened {
    pub fn new(payload: ObservationToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObservationToken {
        &self.0
    }
    pub fn into_payload(self) -> ObservationToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObservationToken> for ObservationOpened {
    fn from(payload: ObservationToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObservationClosed {
    pub fn new(payload: ObservationToken) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObservationToken {
        &self.0
    }
    pub fn into_payload(self) -> ObservationToken {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObservationToken> for ObservationClosed {
    fn from(payload: ObservationToken) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OperationReceived {
    pub fn new(payload: OperationKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &OperationKind {
        &self.0
    }
    pub fn into_payload(self) -> OperationKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<OperationKind> for OperationReceived {
    fn from(payload: OperationKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ScopeReference {
    pub fn path(payload: String) -> Self {
        Self::Path(WirePath::new(payload))
    }
    pub fn task(payload: String) -> Self {
        Self::Task(TaskToken::new(payload))
    }
}

#[rustfmt::skip]
impl ActivityFilter {
    pub fn role_filter(payload: RoleIdentifier) -> Self {
        Self::RoleFilter(RoleName::new(payload))
    }
    pub fn path_prefix(payload: String) -> Self {
        Self::PathPrefix(WirePath::new(payload))
    }
    pub fn task_token(payload: String) -> Self {
        Self::TaskToken(TaskToken::new(payload))
    }
}

#[rustfmt::skip]
impl HandoffRejectionReason {
    pub fn target_role_conflict(payload: Vec<ScopeConflict>) -> Self {
        Self::TargetRoleConflict(ScopeConflicts::new(payload))
    }
}

#[rustfmt::skip]
impl ObservationEvent {
    pub fn operation_received(payload: OperationKind) -> Self {
        Self::OperationReceived(OperationReceived::new(payload))
    }
    pub fn effect_emitted(payload: EffectEmitted) -> Self {
        Self::EffectEmitted(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn claim(payload: RoleClaim) -> Self {
        Self::Claim(payload)
    }
    pub fn release(payload: RoleName) -> Self {
        Self::Release(RoleRelease::new(payload))
    }
    pub fn handoff(payload: RoleHandoff) -> Self {
        Self::Handoff(payload)
    }
    pub fn observe(payload: Observation) -> Self {
        Self::Observe(payload)
    }
    pub fn submit(payload: ActivitySubmission) -> Self {
        Self::Submit(payload)
    }
    pub fn query(payload: ActivityQuery) -> Self {
        Self::Query(payload)
    }
    pub fn watch(payload: ObservationSubscription) -> Self {
        Self::Watch(payload)
    }
    pub fn unwatch(payload: Integer) -> Self {
        Self::Unwatch(ObservationToken::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn claim_acceptance(payload: ClaimAcceptance) -> Self {
        Self::ClaimAcceptance(payload)
    }
    pub fn claim_rejection(payload: ClaimRejection) -> Self {
        Self::ClaimRejection(payload)
    }
    pub fn release_acknowledgment(payload: ReleaseAcknowledgment) -> Self {
        Self::ReleaseAcknowledgment(payload)
    }
    pub fn handoff_acceptance(payload: HandoffAcceptance) -> Self {
        Self::HandoffAcceptance(payload)
    }
    pub fn handoff_rejection(payload: HandoffRejection) -> Self {
        Self::HandoffRejection(payload)
    }
    pub fn role_snapshot(payload: RoleSnapshot) -> Self {
        Self::RoleSnapshot(payload)
    }
    pub fn lanes_observed(payload: LaneRegistrations) -> Self {
        Self::LanesObserved(LanesObserved::new(payload))
    }
    pub fn worktrees_observed(payload: Worktrees) -> Self {
        Self::WorktreesObserved(WorktreesObserved::new(payload))
    }
    pub fn activity_acknowledgment(payload: Integer) -> Self {
        Self::ActivityAcknowledgment(ActivityAcknowledgment::new(payload))
    }
    pub fn activity_list(payload: Activities) -> Self {
        Self::ActivityList(ActivityList::new(payload))
    }
    pub fn partial_applied(payload: PartialApplied) -> Self {
        Self::PartialApplied(payload)
    }
    pub fn observation_opened(payload: ObservationToken) -> Self {
        Self::ObservationOpened(ObservationOpened::new(payload))
    }
    pub fn observation_closed(payload: ObservationToken) -> Self {
        Self::ObservationClosed(ObservationClosed::new(payload))
    }
}

#[rustfmt::skip]
impl From<WirePath> for ScopeReference {
    fn from(payload: WirePath) -> Self {
        Self::Path(payload)
    }
}

#[rustfmt::skip]
impl From<TaskToken> for ScopeReference {
    fn from(payload: TaskToken) -> Self {
        Self::Task(payload)
    }
}

#[rustfmt::skip]
impl From<RoleName> for ActivityFilter {
    fn from(payload: RoleName) -> Self {
        Self::RoleFilter(payload)
    }
}

#[rustfmt::skip]
impl From<WirePath> for ActivityFilter {
    fn from(payload: WirePath) -> Self {
        Self::PathPrefix(payload)
    }
}

#[rustfmt::skip]
impl From<TaskToken> for ActivityFilter {
    fn from(payload: TaskToken) -> Self {
        Self::TaskToken(payload)
    }
}

#[rustfmt::skip]
impl From<ScopeConflicts> for HandoffRejectionReason {
    fn from(payload: ScopeConflicts) -> Self {
        Self::TargetRoleConflict(payload)
    }
}

#[rustfmt::skip]
impl From<OperationReceived> for ObservationEvent {
    fn from(payload: OperationReceived) -> Self {
        Self::OperationReceived(payload)
    }
}

#[rustfmt::skip]
impl From<EffectEmitted> for ObservationEvent {
    fn from(payload: EffectEmitted) -> Self {
        Self::EffectEmitted(payload)
    }
}

#[rustfmt::skip]
impl From<RoleClaim> for Input {
    fn from(payload: RoleClaim) -> Self {
        Self::Claim(payload)
    }
}

#[rustfmt::skip]
impl From<RoleRelease> for Input {
    fn from(payload: RoleRelease) -> Self {
        Self::Release(payload)
    }
}

#[rustfmt::skip]
impl From<RoleHandoff> for Input {
    fn from(payload: RoleHandoff) -> Self {
        Self::Handoff(payload)
    }
}

#[rustfmt::skip]
impl From<Observation> for Input {
    fn from(payload: Observation) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl From<ActivitySubmission> for Input {
    fn from(payload: ActivitySubmission) -> Self {
        Self::Submit(payload)
    }
}

#[rustfmt::skip]
impl From<ActivityQuery> for Input {
    fn from(payload: ActivityQuery) -> Self {
        Self::Query(payload)
    }
}

#[rustfmt::skip]
impl From<ObservationSubscription> for Input {
    fn from(payload: ObservationSubscription) -> Self {
        Self::Watch(payload)
    }
}

#[rustfmt::skip]
impl From<ObservationToken> for Input {
    fn from(payload: ObservationToken) -> Self {
        Self::Unwatch(payload)
    }
}

#[rustfmt::skip]
impl From<ClaimAcceptance> for Output {
    fn from(payload: ClaimAcceptance) -> Self {
        Self::ClaimAcceptance(payload)
    }
}

#[rustfmt::skip]
impl From<ClaimRejection> for Output {
    fn from(payload: ClaimRejection) -> Self {
        Self::ClaimRejection(payload)
    }
}

#[rustfmt::skip]
impl From<ReleaseAcknowledgment> for Output {
    fn from(payload: ReleaseAcknowledgment) -> Self {
        Self::ReleaseAcknowledgment(payload)
    }
}

#[rustfmt::skip]
impl From<HandoffAcceptance> for Output {
    fn from(payload: HandoffAcceptance) -> Self {
        Self::HandoffAcceptance(payload)
    }
}

#[rustfmt::skip]
impl From<HandoffRejection> for Output {
    fn from(payload: HandoffRejection) -> Self {
        Self::HandoffRejection(payload)
    }
}

#[rustfmt::skip]
impl From<RoleSnapshot> for Output {
    fn from(payload: RoleSnapshot) -> Self {
        Self::RoleSnapshot(payload)
    }
}

#[rustfmt::skip]
impl From<LanesObserved> for Output {
    fn from(payload: LanesObserved) -> Self {
        Self::LanesObserved(payload)
    }
}

#[rustfmt::skip]
impl From<WorktreesObserved> for Output {
    fn from(payload: WorktreesObserved) -> Self {
        Self::WorktreesObserved(payload)
    }
}

#[rustfmt::skip]
impl From<ActivityAcknowledgment> for Output {
    fn from(payload: ActivityAcknowledgment) -> Self {
        Self::ActivityAcknowledgment(payload)
    }
}

#[rustfmt::skip]
impl From<ActivityList> for Output {
    fn from(payload: ActivityList) -> Self {
        Self::ActivityList(payload)
    }
}

#[rustfmt::skip]
impl From<PartialApplied> for Output {
    fn from(payload: PartialApplied) -> Self {
        Self::PartialApplied(payload)
    }
}

#[rustfmt::skip]
impl From<ObservationOpened> for Output {
    fn from(payload: ObservationOpened) -> Self {
        Self::ObservationOpened(payload)
    }
}

#[rustfmt::skip]
impl From<ObservationClosed> for Output {
    fn from(payload: ObservationClosed) -> Self {
        Self::ObservationClosed(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_CLAIM: u64 = 0x0000000000000000;
    pub const INPUT_RELEASE: u64 = 0x0001000000000000;
    pub const INPUT_HANDOFF: u64 = 0x0002000000000000;
    pub const INPUT_OBSERVE: u64 = 0x0003000000000000;
    pub const INPUT_SUBMIT: u64 = 0x0004000000000000;
    pub const INPUT_QUERY: u64 = 0x0005000000000000;
    pub const INPUT_WATCH: u64 = 0x0006000000000000;
    pub const INPUT_UNWATCH: u64 = 0x0007000000000000;
    pub const OUTPUT_CLAIM_ACCEPTANCE: u64 = 0x0100000000000000;
    pub const OUTPUT_CLAIM_REJECTION: u64 = 0x0101000000000000;
    pub const OUTPUT_RELEASE_ACKNOWLEDGMENT: u64 = 0x0102000000000000;
    pub const OUTPUT_HANDOFF_ACCEPTANCE: u64 = 0x0103000000000000;
    pub const OUTPUT_HANDOFF_REJECTION: u64 = 0x0104000000000000;
    pub const OUTPUT_ROLE_SNAPSHOT: u64 = 0x0105000000000000;
    pub const OUTPUT_LANES_OBSERVED: u64 = 0x0106000000000000;
    pub const OUTPUT_WORKTREES_OBSERVED: u64 = 0x0107000000000000;
    pub const OUTPUT_ACTIVITY_ACKNOWLEDGMENT: u64 = 0x0108000000000000;
    pub const OUTPUT_ACTIVITY_LIST: u64 = 0x0109000000000000;
    pub const OUTPUT_PARTIAL_APPLIED: u64 = 0x010A000000000000;
    pub const OUTPUT_OBSERVATION_OPENED: u64 = 0x010B000000000000;
    pub const OUTPUT_OBSERVATION_CLOSED: u64 = 0x010C000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Claim,
    Release,
    Handoff,
    Observe,
    Submit,
    Query,
    Watch,
    Unwatch,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    ClaimAcceptance,
    ClaimRejection,
    ReleaseAcknowledgment,
    HandoffAcceptance,
    HandoffRejection,
    RoleSnapshot,
    LanesObserved,
    WorktreesObserved,
    ActivityAcknowledgment,
    ActivityList,
    PartialApplied,
    ObservationOpened,
    ObservationClosed,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Claim(_) => InputRoute::Claim,
            Self::Release(_) => InputRoute::Release,
            Self::Handoff(_) => InputRoute::Handoff,
            Self::Observe(_) => InputRoute::Observe,
            Self::Submit(_) => InputRoute::Submit,
            Self::Query(_) => InputRoute::Query,
            Self::Watch(_) => InputRoute::Watch,
            Self::Unwatch(_) => InputRoute::Unwatch,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Claim(_) => short_header::INPUT_CLAIM,
            Self::Release(_) => short_header::INPUT_RELEASE,
            Self::Handoff(_) => short_header::INPUT_HANDOFF,
            Self::Observe(_) => short_header::INPUT_OBSERVE,
            Self::Submit(_) => short_header::INPUT_SUBMIT,
            Self::Query(_) => short_header::INPUT_QUERY,
            Self::Watch(_) => short_header::INPUT_WATCH,
            Self::Unwatch(_) => short_header::INPUT_UNWATCH,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_CLAIM => Ok(InputRoute::Claim),
            short_header::INPUT_RELEASE => Ok(InputRoute::Release),
            short_header::INPUT_HANDOFF => Ok(InputRoute::Handoff),
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            short_header::INPUT_SUBMIT => Ok(InputRoute::Submit),
            short_header::INPUT_QUERY => Ok(InputRoute::Query),
            short_header::INPUT_WATCH => Ok(InputRoute::Watch),
            short_header::INPUT_UNWATCH => Ok(InputRoute::Unwatch),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::ClaimAcceptance(_) => OutputRoute::ClaimAcceptance,
            Self::ClaimRejection(_) => OutputRoute::ClaimRejection,
            Self::ReleaseAcknowledgment(_) => OutputRoute::ReleaseAcknowledgment,
            Self::HandoffAcceptance(_) => OutputRoute::HandoffAcceptance,
            Self::HandoffRejection(_) => OutputRoute::HandoffRejection,
            Self::RoleSnapshot(_) => OutputRoute::RoleSnapshot,
            Self::LanesObserved(_) => OutputRoute::LanesObserved,
            Self::WorktreesObserved(_) => OutputRoute::WorktreesObserved,
            Self::ActivityAcknowledgment(_) => OutputRoute::ActivityAcknowledgment,
            Self::ActivityList(_) => OutputRoute::ActivityList,
            Self::PartialApplied(_) => OutputRoute::PartialApplied,
            Self::ObservationOpened(_) => OutputRoute::ObservationOpened,
            Self::ObservationClosed(_) => OutputRoute::ObservationClosed,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::ClaimAcceptance(_) => short_header::OUTPUT_CLAIM_ACCEPTANCE,
            Self::ClaimRejection(_) => short_header::OUTPUT_CLAIM_REJECTION,
            Self::ReleaseAcknowledgment(_) => short_header::OUTPUT_RELEASE_ACKNOWLEDGMENT,
            Self::HandoffAcceptance(_) => short_header::OUTPUT_HANDOFF_ACCEPTANCE,
            Self::HandoffRejection(_) => short_header::OUTPUT_HANDOFF_REJECTION,
            Self::RoleSnapshot(_) => short_header::OUTPUT_ROLE_SNAPSHOT,
            Self::LanesObserved(_) => short_header::OUTPUT_LANES_OBSERVED,
            Self::WorktreesObserved(_) => short_header::OUTPUT_WORKTREES_OBSERVED,
            Self::ActivityAcknowledgment(_) => {
                short_header::OUTPUT_ACTIVITY_ACKNOWLEDGMENT
            }
            Self::ActivityList(_) => short_header::OUTPUT_ACTIVITY_LIST,
            Self::PartialApplied(_) => short_header::OUTPUT_PARTIAL_APPLIED,
            Self::ObservationOpened(_) => short_header::OUTPUT_OBSERVATION_OPENED,
            Self::ObservationClosed(_) => short_header::OUTPUT_OBSERVATION_CLOSED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_CLAIM_ACCEPTANCE => Ok(OutputRoute::ClaimAcceptance),
            short_header::OUTPUT_CLAIM_REJECTION => Ok(OutputRoute::ClaimRejection),
            short_header::OUTPUT_RELEASE_ACKNOWLEDGMENT => {
                Ok(OutputRoute::ReleaseAcknowledgment)
            }
            short_header::OUTPUT_HANDOFF_ACCEPTANCE => Ok(OutputRoute::HandoffAcceptance),
            short_header::OUTPUT_HANDOFF_REJECTION => Ok(OutputRoute::HandoffRejection),
            short_header::OUTPUT_ROLE_SNAPSHOT => Ok(OutputRoute::RoleSnapshot),
            short_header::OUTPUT_LANES_OBSERVED => Ok(OutputRoute::LanesObserved),
            short_header::OUTPUT_WORKTREES_OBSERVED => Ok(OutputRoute::WorktreesObserved),
            short_header::OUTPUT_ACTIVITY_ACKNOWLEDGMENT => {
                Ok(OutputRoute::ActivityAcknowledgment)
            }
            short_header::OUTPUT_ACTIVITY_LIST => Ok(OutputRoute::ActivityList),
            short_header::OUTPUT_PARTIAL_APPLIED => Ok(OutputRoute::PartialApplied),
            short_header::OUTPUT_OBSERVATION_OPENED => Ok(OutputRoute::ObservationOpened),
            short_header::OUTPUT_OBSERVATION_CLOSED => Ok(OutputRoute::ObservationClosed),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Claim",
        "Release",
        "Handoff",
        "Observe",
        "Submit",
        "Query",
        "Watch",
        "Unwatch",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
